### ISSUE TITLE
Message from Twitch instead of ad

### ISSUE THREAD

**Issue by solidbird** [revzim/ttv-ad-less-standalone#1]
I don't know why but today I got a message from twitch instead of ad... at least I could watch the stream after 1 or 2 minutes.

Here is the screenshot I made during this thing:
https://imgur.com/8kZjOqT

**Comment by revzim** [comment]
Interesting, I have never seen this before and just tested a few streams just now and did not see that message. That makes me believe it most likely has something to do with whatever addons/extensions you have installed on your browser.

If you want an immediate fix, I developed a simple electron application for ad-free viewing: 
[ttv-viewer repo](https://github.com/revzim/ttv-viewer) & [ttv-viewer releases](https://github.com/revzim/ttv-viewer/releases) . Windows 10 & MacOS versions are available through the releases page.

I am closing this issue; however, if after disabling all addons/extensions and testing the streams again and the issue still persists, feel free to open an issue again. Next time, please provide some information about your setup. e.g. browser, addons/extensions, streams/broadcasts queried, etc. Thanks!

**Comment by solidbird** [comment]
Thank you
